src/RMS/RecoveryBundle/Entity/HealthStatus.php
<?php

namespace RMS\RecoveryBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @author Randolph Roble <r.roble@arcanys.com>
 * @ORM\Table(name="health_status")
 * @ORM\Entity()
 */
class HealthStatus extends AbstractTimestamptable
{

    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * 
     * @var integer
     */
    protected $id;

    /**
     * @ORM\ManyToOne(targetEntity="Ngo", inversedBy="reportedMessages", cascade={"persist"})
     * @ORM\JoinColumn(name="ngo_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     * 
     * @var Ngo
     */
    protected $reporter;

    /**
     * @ORM\ManyToOne(targetEntity="HealthLocation", inversedBy="messages", cascade={"persist"})
     * @ORM\JoinColumn(name="location_id", referencedColumnName="id", nullable=false, onDelete="CASCADE")
     * 
     * @var HealthLocation
     */
    protected $location;

    /**
     * @ORM\Column(name="message", type="text", nullable=false)
     * @Assert\NotBlank()
     * @Assert\Length(max=200)
     * 
     * @var string
     */
    protected $message;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @return Ngo
     */
    public function getReporter()
    {
        return $this->reporter;
    }

    public function setReporter(Ngo $reporter)
    {
        $this->reporter = $reporter;
    }

    /**
     * @return HealthLocation
     */
    public function getLocation()
    {
        return $this->location;
    }

    public function setLocation(HealthLocation $location)
    {
        $this->location = $location;
    }

    public function getMessage()
    {
        return $this->message;
    }

    public function setMessage($message)
    {
        $this->message = $message;
    }
    
    public function __toString()
    {
        if (isset($this->message[50])) {
            return substr($this->message, 0, 50).' ...';
        }
        return $this->message.'';
    }

    public function getDate()
    {
        return $this->dateCreated;
    }
    
}

src/RMS/RecoveryBundle/Entity/Ngo.php
<?php

namespace RMS\RecoveryBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use RMS\RecoveryBundle\Model\Enums;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Ngo
 *
 * @ORM\Table(name="ngo", uniqueConstraints={
 *      @ORM\UniqueConstraint(name="unique_name_idx", columns={"name"})
 * })
 * @ORM\Entity()
 * @UniqueEntity("name")
 */
class Ngo extends AbstractTimestamptable implements Timestamptable
{

    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * 
     * @var integer
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", length=45, nullable=false)
     * 
     * @var string
     */
    protected $name;

    /**
     * @ORM\Column(name="logo", type="string", length=255, nullable=true)
     * @Assert\Url()
     * 
     * @var string
     */
    protected $logo;

    /**
     * @ORM\Column(name="description", type="text", nullable=true)
     * @Assert\Length(max=200)
     * 
     * @var string
     */
    protected $description;

    /**
     * @ORM\Column(name="street", type="string", length=45, nullable=true)
     * 
     * @var string
     */
    protected $street;

    /**
     * @ORM\Column(name="city", type="string", length=45, nullable=true)
     * 
     * @var string
     */
    protected $city;

    /**
     * @ORM\Column(name="country", type="string", length=45, nullable=true)
     * 
     * @var string
     */
    protected $country;

    /**
     * @ORM\Column(name="zipcode", type="string", length=45, nullable=true)
     * 
     * @var string
     */
    protected $zipcode;

    /**
     * @ORM\Column(name="verification_status", type="boolean", nullable=true)
     * 
     * @var boolean
     */
    protected $status;

    /**
     * @ORM\OneToMany(targetEntity="Aid", mappedBy="ngo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $aids;
    
    /**
     * @ORM\OneToMany(targetEntity="UserNgo", mappedBy="ngo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $users;

    /**
     * @ORM\Column(name="website", type="string", nullable=true, length=255)
     * @Assert\Url()
     * 
     * @var boolean
     */
    protected $website;

    /**
     * @ORM\Column(name="ngo_type", type="string", length=45, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Choice(callback = {"RMS\RecoveryBundle\Model\Enums", "validNgoTypes"})
     * 
     * @var string
     */
    protected $ngoType;

    /**
     * @ORM\Column(name="skills", type="simple_array", nullable=true)
     * 
     * @var array
     */
    protected $skills;
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->aids = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->ngoType = Enums::NGO_TYPE_PRIVATE;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Ngo
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set logo
     *
     * @param string $logo
     * @return Ngo
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get logo
     *
     * @return string 
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Ngo
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set street
     *
     * @param string $street
     * @return Ngo
     */
    public function setStreet($street)
    {
        $this->street = $street;

        return $this;
    }

    /**
     * Get street
     *
     * @return string 
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * Set city
     *
     * @param string $city
     * @return Ngo
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string 
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set country
     *
     * @param string $country
     * @return Ngo
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return string 
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set zipcode
     *
     * @param string $zipcode
     * @return Ngo
     */
    public function setZipcode($zipcode)
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    /**
     * Get zipcode
     *
     * @return string 
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }

    /**
     * Set status
     *
     * @param boolean $status
     * @return Ngo
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return boolean 
     */
    public function getStatus()
    {
        return $this->status;
    }
    
    /**
     * @return boolean
     */
    public function isVerified()
    {
        return $this->status;
    }

    public function __toString()
    {
        return $this->name.'';
    }

    /**
     * Add aid
     *
     * @param Aid $aid
     * @return Ngo
     */
    public function addAid(Aid $aid)
    {
        $this->aids[] = $aid;

        return $this;
    }

    /**
     * Remove aid
     *
     * @param Aid $aid
     */
    public function removeAid(Aid $aid)
    {
        $this->aids->removeElement($aid);
    }

    /**
     * Get aids
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAids()
    {
        return $this->aids;
    }

    /**
     * Add user
     *
     * @param UserNgo $user
     * @return Ngo
     */
    public function addUser(UserNgo $user)
    {
        $this->users[] = $user;

        return $this;
    }

    /**
     * Remove user
     *
     * @param UserNgo $user
     */
    public function removeUser(UserNgo $user)
    {
        $this->users->removeElement($user);
    }

    /**
     * Get users
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * @return string
     */
    public function getWebsite()
    {
        return $this->website;
    }

    public function setWebsite($website)
    {
        $this->website = $website;
    }

    public function getNgoType()
    {
        return $this->ngoType;
    }

    public function setNgoType($ngoType)
    {
        $this->ngoType = $ngoType;
        
        return $this;
    }

    /**
     * @return array
     */
    public function getSkills()
    {
        return $this->skills;
    }

    public function setSkills(array $skills)
    {
        $this->skills = $skills;
        
        return $this;
    }

    /**
     * @return boolean
     */
    public function isHealthNgo()
    {
        return $this->ngoType == Enums::NGO_TYPE_HEALTH;
    }
    
}

src/RMS/RecoveryBundle/Form/HealthStatusType.php
<?php

namespace RMS\RecoveryBundle\Form;

use Doctrine\ORM\EntityRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class HealthStatusType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
                ->add('message', 'textarea', array(
					'label' => 'Message *',
                    'attr' => array('class' => 'form-control', 'rows'=> '4', 'maxlength' => '200' )
                ))
                ->add('location', null, array(
					'label' => 'Location *',
                    'attr' => array('class' => 'form-control'),
                    'query_builder' => function(EntityRepository $er) {
                        $qb = $er->createQueryBuilder('l')
                                ->leftJoin('l.province', 'p')
                                ->orderBy('p.name', 'ASC')
                                ->addOrderBy('l.name', 'ASC');
                        return $qb;
                    },
                    'property' => 'locationName',
                ))
        ;
    }

    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'RMS\RecoveryBundle\Entity\HealthStatus',
            'request' => null,
        ));
        $resolver->addAllowedTypes(array(
            'request' => 'Symfony\Component\HttpFoundation\Request',
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'rms_recoverybundle_healthstatus';
    }

}

src/RMS/RecoveryBundle/Controller/HealthStatusController.php
<?php

namespace RMS\RecoveryBundle\Controller;

use RMS\RecoveryBundle\Entity\HealthStatus;
use RMS\RecoveryBundle\Form\HealthStatusType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;

/**
 * @author Dottie Decano <d.decano@arcanys.com>
 * @Route("/health/status")
 */
class HealthStatusController extends Controller
{

    /**
     * @Route("/", name="health_status")
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->getDoctrine()->getManager();
        $qb = $em->getRepository('RMSRecoveryBundle:HealthStatus')->createQueryBuilder('s');
        $qb->select('s')
                ->leftJoin('s.location', 'l')
                ->leftJoin('l.province', 'p')
                ->orderBy('l.name', 'ASC')
                ->addOrderBy('s.dateCreated', 'DESC');


        $request = $this->getRequest();
        $session = $request->getSession();
        $filters = $session->get($filterKey = 'attr_hd_province');
        if ($request->query->has('_p')) {
            $filters = array($request->get('_p'));
            $session->set($filterKey, $filters);
        }
        if ($filters) {
            $qb->where($qb->expr()->in('p.id', $filters));
        } else {
            $qb->setMaxResults(0);
        }

        $locations = array();
		$list = $qb->getQuery()->getResult();
        foreach ($list as $status) {
            $location = $status->getLocation();
            $id = $location->getId();
            if (!isset($locations[$id])) {
                $locations[$id] = array(
                    'location' => $location,
                    'messages' => array(),
                );
            }
            $locations[$id]['messages'][] = $status;
        }
        $provinces = $em->getRepository('RMSRecoveryBundle:Province')
                ->findBy(array(), array('name' => 'ASC'));
        $result = array(
            'locations' => $locations,
			'provinces' => $provinces,
			'filters' => $filters,
        );
        if ($request->isXmlHttpRequest()) {
            return $this->render('RMSRecoveryBundle:HealthStatus:statusContent.html.twig', $result);
        }
		return $result;
    }

    /**
     * @Route("/add", name="add_health_status")
     * @Template()
     */
    public function addHealthStatusAction(Request $request)
    {
        $user = $this->getUser();
        $status = new HealthStatus();
        $status->setReporter($user->getNgo());

        $form = $this->createForm(new HealthStatusType(), $status, array('request' => $request));

        if ($request->isMethod('post'))
        {
            $form->handleRequest($request);
            if ($form->isValid())
            {
                $em = $this->getDoctrine()->getManager();
                $em->persist($status);
                $em->flush();
                return $this->redirect($this->generateUrl('add_health_status_success'));
            }
        }

        return array(
            'form' => $form->createView(),
            'status' => $status,
        );
    }

    /**
     * @Route("/add-success", name="add_health_status_success")
     * @Template()
     */
    public function successAction()
    {
        return array();
    }
}

src/RMS/RecoveryBundle/Resources/views/HealthStatus/_js.html.twig
<script type="text/javascript">
jQuery(function($) {

    $(document).on("click", '#add-health-status', function() {
        var cont = $('#entry-container');
        cont.stop().toggle();
        return false;
    });

    $(document).on("submit", "#add-entry-form", function() {
        var $this = $(this), action = $this.attr("action");
        $(".alert-success", "#entry-container").remove();
        $(".new-entry-loader").show();
        $.post(action+"?r="+Math.random(), $this.serialize(), function(data) {
            $("#entry-container").html(data);
            loadpicker();
        });
        return false;
    });

    var xhr, tmr;
    $(document).on("change", ".filter-province", function() {
        var id = $(this).val();
        var url = "{{ path('health_status') }}?r="+Math.random()+"&_p="+id;
        if (tmr) clearTimeout(tmr);
        tmr = setTimeout(function() {
            $(".hdloader").show();
            if (xhr && xhr.readyState != 4) xhr.abort();
            $(".maintable").hide();
            xhr = $.get(url, function(data) {
                $("#hdcontent").html(data);
            });
        }, 200);
    });
});
</script>

src/RMS/RecoveryBundle/Resources/views/HealthStatus/addHealthStatus.html.twig
<div class="row add-health-status">
    <div class="pane alert alert-warning">
        <h3>
            Post Message
            <img style="display:none;" class="right new-entry-loader" src="{{ asset('bundles/rmsrecovery/images/ajax-loader_blue.gif') }}" alt="">
        </h3>
        {{ form_errors(form) }}

		<form role="form" id="add-entry-form" method="POST" action="{{ path('add_health_status') }}">
            <div class="row">
                <div class="col-xs-4 col-xs-no-padding-right">
                    <div class="form-group">
                        <label for="NGO">NGO</label>
                        <input type="text" class="form-control" placeholder="NGO" value="{{ status.reporter }}" disabled="disabled">
                    </div>
                </div>
                <div class="col-xs-4 col-xs-no-padding-right">
                    <div class="form-group">
						{{ form_label(form.location) }}
						{{ form_widget(form.location) }}
                    </div>
                </div>
			</div>
            <div class="row">
                <div class="col-xs-10 col-xs-no-padding-right">
                    <div class="form-group">
						{{ form_label(form.message) }}
						{{ form_widget(form.message) }}
                    </div>
                </div>
			</div>

			<div class="row"><br></div>

			<div class="row" style="">
				<div class="col-xs-12">
					<button type="submit" class="btn btn-lg btn-success right">Save</button>
				</div>
			</div>

		{{ form_rest(form) }}
		</form>
	</div>
</div>

src/RMS/RecoveryBundle/Resources/views/HealthStatus/index.html.twig
{% extends "RMSRecoveryBundle::layout.html.twig" %}
{% block nav_tabs %}
    {{ _this.nav_tabs('health') }}
{% endblock %}

{% block stylesheets_custom %}
<link rel="stylesheet" type="text/css" href="{{ asset('bundles/rmsrecovery/css/health-team-distribution.css') }}" />
{% endblock stylesheets_custom %}

{% block content %}
<div class="container c-border" id="health-status">


    <div class="row health-status-wrapper">
		<div class="row ph-header-2">
			<div class="col-md-7">
				<a href="{{ path('health_team_distribution') }}" class="title-link">
					<h2 class="title inactive"><img src="{{ asset('bundles/rmsrecovery/images/health-grey.png') }}">{{ 'Medical Team Distribution'|trans }}</h2>
				</a>
				<h2 class="title2 active">Message Board</h2>
			</div>

			<!--<div class="col-md-7 text-right">
				{% if app.user is not null and is_granted('ROLE_NGO') and app.user.ngo.healthNgo and app.user.coordinator %}
				<div class="btn-group">
					<button type="button" class="btn btn-default dropdown-toggle btn-lg" data-toggle="dropdown">
						Message Board <span class="caret"></span>
					</button>
					<ul class="dropdown-menu" role="menu">
						<li><a href="{{ path('health_team_distribution') }}">Health Team Distribution</a></li>
						<li><a href="{{ path('health_team_manage') }}">Manage Teams</a></li>
					</ul>
				</div>
				<a id="add-health-status" href="{{ path('add_health_status') }}" class="btn btn-success btn-lg">Post Message</a>
				{% endif %}
			</div>-->

			<div class="col-md-5 text-right">
				{% if app.user is not null and is_granted('ROLE_NGO') and app.user.ngo.healthNgo and app.user.coordinator %}
                <a href="{{ path('health_team_manage') }}" class="btn btn-lg btn-warning">Manage Teams</a>
				<a id="add-health-status" href="{{ path('add_health_status') }}" class="btn btn-success btn-lg">Post Message</a>
				{% endif %}
			</div>
		</div>
	</div>
</div>

	<div class="row health-status-wrapper">
	{# todo: is coordinator #}
	{% if app.user is not null and is_granted('ROLE_NGO') and app.user.ngo.healthNgo and app.user.coordinator %}
		<div id="entry-container" style="display:none;">
			{% render(controller("RMSRecoveryBundle:HealthStatus:addHealthStatus")) %}
		</div>
	{% endif %}
	{% if app.user is null %}
			<div class="alert alert-warning">
				You must be logged in and be part of a Health NGO in order to access this information.
				<a href="{{ path('login') }}">Sign in</a>
			</div>
	{% else %}
		{% if is_granted('ROLE_NGO') %}
			{% if not app.user.ngo.healthNgo %}
			<div class="alert alert-warning">
				This section can only be accessed by health organizations authorized by the Department of Health. If you believe you should be authorized, please contact the live chat.
			</div>
			{% else %}
				{% block health_content %}
				{% include "RMSRecoveryBundle:HealthTeam:_provinces.html.twig" %}
				<div id="hdcontent">
					{% include "RMSRecoveryBundle:HealthStatus:statusContent.html.twig" %}
				</div>
				{% endblock %}
			{% endif %}
		{% endif %}
	{% endif %}
	</div>

	<div class="cb spacer"></div>
{% endblock %}

{% block javascripts %}
{{ parent() }}
{% include "RMSRecoveryBundle:HealthStatus:_js.html.twig" %}
{% endblock %}

src/RMS/RecoveryBundle/Resources/views/HealthStatus/statusContent.html.twig
	<img style="display:none;" class="pull-right hdloader" src="{{ asset('bundles/rmsrecovery/images/ajax-loader_blue.gif') }}" alt="">
	{% for row in locations %}
		<h3>{{ row['location'] }}</h3>
		<hr>
		<div class="row ph-header-2">
			<div class="col-md-3 text-right comp-right">
			</div>
			<div class="col-md-9">
				<div class="padding-left">Latest Update</div>
			</div>
		</div>
		{% for message in row['messages'] %}
			<div class="row ph-header-2">
				<div class="col-md-3 text-right comp-right">
					<h4 class="name">{{ message.reporter }}</h4>
					on {{ message.date|date('M jS, H:ia') }}
				</div>
				<div class="col-md-9">
					<div class="popover right description">
						<div class="arrow"></div>
						<div class="popover-content">
							{{ message.message }}
						</div>
					</div>
					<div class="padding-left see-prev"> </div>
				</div>
			</div>
		{% endfor %}
		<div class="row ph-header-2">
			<div class="col-md-3 text-right comp-right">
			</div>
			<div class="col-md-9">
				<div class="popover right">
				</div>
				{#<div class="padding-left see-prev"><a href="#">See Prevoius Updates for {{ row['location'] }}</a></div>#}
			</div>
		</div>
		<hr>
	{% else %}
		{% if filters|length > 0 %}
		<span class="text-muted">No results found.</span>
		{% endif %}
	{% endfor %}

src/RMS/RecoveryBundle/Resources/views/HealthStatus/success.html.twig
<div class="row">
    <div class="alert alert-success">
        <strong>Success!</strong> Status added successfully.
    </div>
</div>
{% render(controller("RMSRecoveryBundle:HealthStatus:addHealthStatus")) %}