src/RMS/RecoveryBundle/Entity/Geo.php
<?php

namespace RMS\RecoveryBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use RMS\RecoveryBundle\Model\AidManager;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Geo
 *
 * @ORM\Table(name="geo")
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *      "province" = "Province",
 *      "municipality" = "Municipality",
 *      "barangay" = "Barangay",
 * })
 */
abstract class Geo extends AbstractTimestamptable implements Timestamptable
{

    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * 
     * @var integer
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", length=64, nullable=false)
     * @Assert\NotBlank()
     * 
     * @var string
     */
    protected $name;

    /**
     * @ORM\Column(name="map", type="text", nullable=true)
     * 
     * @var string
     */
    protected $map;

    /**
     * @ORM\OneToMany(targetEntity="Situation", mappedBy="geo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $situations;

    /**
     * @ORM\OneToMany(targetEntity="MessageBoard", mappedBy="geo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $messages;

    /**
     * @ORM\OneToMany(targetEntity="AidNeeded", mappedBy="geo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $aidsNeeded;

    /**
     * @ORM\OneToMany(targetEntity="Aid", mappedBy="geo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $aids;

    /**
     * @ORM\Column(name="population", type="float", nullable=true)
     * 
     * @var float
     */
    protected $population;

    /**
     * @ORM\Column(name="estimated_households", type="integer", nullable=true)
     * 
     * @var integer
     */
    protected $estimatedHouseholds;

    /**
     * @ORM\Column(name="affected_households", type="integer", nullable=true)
     * 
     * @var integer
     */
    protected $affectedHouseholds;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->situations = new ArrayCollection();
        $this->aidsNeeded = new ArrayCollection();
        $this->aids = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Barangay
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set map
     *
     * @param string $map
     * @return Geo
     */
    public function setMap($map)
    {
        $this->map = $map;

        return $this;
    }

    /**
     * Get map
     *
     * @return string 
     */
    public function getMap()
    {
        return $this->map;
    }

    /**
     * Add situations
     *
     * @param Situation $situation
     * @return Geo
     */
    public function addSituation(Situation $situation)
    {
        $situation->setGeo($this);
        $this->situations[] = $situation;

        return $this;
    }

    /**
     * Remove situations
     *
     * @param Situation $situation
     */
    public function removeSituation(Situation $situation)
    {
        $this->situations->removeElement($situation);
    }

    /**
     * Get situations
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getSituations()
    {
        $situations = $this->situations->getValues();
        uasort($situations, function(Situation $a, Situation $b) {
            if ($a->getDate() == $b->getDate()) {
                return 0;
            }
            return ($a->getDate() > $b->getDate()) ? -1 : 1;
        });
        return $situations;
    }

    /**
     * Get situations
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMessages()
    {
        $messages = $this->messages->getValues();
        uasort($messages, function(MessageBoard $a, MessageBoard $b) {
            if ($a->getDate() == $b->getDate()) {
                return 0;
            }
            return ($a->getDate() > $b->getDate()) ? -1 : 1;
        });
        return $messages;
    }

    /**
     * Add aidsNeeded
     *
     * @param AidNeeded $need
     * @return Geo
     */
    public function addNeed(AidNeeded $need)
    {
        $need->setGeo($this);
        $this->aidsNeeded[] = $need;

        return $this;
    }

    /**
     * Remove aidsNeeded
     *
     * @param AidNeeded $need
     */
    public function removeNeed(AidNeeded $need)
    {
        $this->aidsNeeded->removeElement($need);
    }

    /**
     * Get aidsNeeded
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAidsNeeded()
    {
        return $this->aidsNeeded;
    }

    /**
     * Add aid
     *
     * @param Aid $aid
     * @return Geo
     */
    public function addAid(Aid $aid)
    {
        $this->aids[] = $aid;

        return $this;
    }

    /**
     * Remove aid
     *
     * @param Aid $aid
     */
    public function removeAid(Aid $aid)
    {
        $this->aids->removeElement($aid);
    }

    /**
     * Get aids
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAids()
    {
        return $this->sortAids($this->aids->getValues());
    }
    
    public function __toString()
    {
        return $this->id;
    }
    
    public abstract function getOptionLevel($text);
    
    public function getOptionName()
    {
        return $this->getOptionLevel('. ').' '.$this->__toString();
    }

    /**
     * Set population
     *
     * @param float $population
     * @return Barangay
     */
    public function setPopulation($population)
    {
        $this->population = $population;

        return $this;
    }

    /**
     * Get population
     *
     * @return float 
     */
    public function getPopulation()
    {
        return $this->population;
    }

    /**
     * Set estimatedHouseholds
     *
     * @param integer $estimatedHouseholds
     * @return Barangay
     */
    public function setEstimatedHouseholds($estimatedHouseholds)
    {
        $this->estimatedHouseholds = $estimatedHouseholds;

        return $this;
    }

    /**
     * Get estimatedHouseholds
     *
     * @return integer 
     */
    public function getEstimatedHouseholds()
    {
        return $this->estimatedHouseholds;
    }

    /**
     * Set affectedHouseholds
     *
     * @param integer $affectedHouseholds
     * @return Barangay
     */
    public function setAffectedHouseholds($affectedHouseholds)
    {
        $this->affectedHouseholds = $affectedHouseholds;

        return $this;
    }

    /**
     * Get affectedHouseholds
     *
     * @return integer 
     */
    public function getAffectedHouseholds()
    {
        return $this->affectedHouseholds;
    }
    
    public abstract function hasActivities(AidManager $mgr);
 
    public function lastReport()
    {
        if (count($this->aids) > 0) {
            return $this->aids->last();
        }
    }
    
    public function isProvince()
    {
        return $this instanceof Province;
    }
    
    public function isMunicipality()
    {
        return $this instanceof Municipality;
    }
    
    public function isBarangay()
    {
        return $this instanceof Barangay;
    }
    
    public function getActiveNgos()
    {
        $result = array();
        foreach ($this->aids->getValues() as $aid) {
            $ngo = $aid->getNgo();
            $result[$ngo->getId()] = $ngo;
        }
        return $result;
    }
    
    protected function sortAids($aids)
    {
        $sorter = function(Aid $a, Aid $b) {
            if ($a->getDateStart() == $b->getDateStart()) {
                return 0;
            }
            return ($a->getDateStart() > $b->getDateStart()) ? -1 : 1;
        };
        uasort($aids, $sorter);
        return $aids;
    }

    /**
     * @return integer
     */
    public abstract function getMapZoom();
    
    public function getLatitude()
    {
        $coords = $this->getCoords();
        if (!$coords || count($coords) == 0) {
            return '10.633614991656064';
        }
        $l = array();
        foreach ($coords as $c) $l[] = $c->lat;
        return array_sum($l)/count($l);
    }
    
    public function getLongitude()
    {
        $coords = $this->getCoords();
        if (!$coords || count($coords) == 0) {
            return '123.93951416015626';
        }
        $l = array();
        foreach ($coords as $c) $l[] = $c->lng;
        return array_sum($l)/count($l);
    }
    
    public function getCoords()
    {
        if ($this->map) {
            $coords = array();
            $latlng = explode(';', $this->map);
            foreach ($latlng as $ll) {
                list($lat,$lng) = explode(',', $ll);
                $coords[] = (object) array('lat' => $lat, 'lng' => $lng);
            }
            return $coords;
        }
    }
}

src/RMS/RecoveryBundle/Entity/Ngo.php
<?php

namespace RMS\RecoveryBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use RMS\RecoveryBundle\Model\Enums;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;

/**
 * Ngo
 *
 * @ORM\Table(name="ngo", uniqueConstraints={
 *      @ORM\UniqueConstraint(name="unique_name_idx", columns={"name"})
 * })
 * @ORM\Entity()
 * @UniqueEntity("name")
 */
class Ngo extends AbstractTimestamptable implements Timestamptable
{

    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * 
     * @var integer
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", length=45, nullable=false)
     * 
     * @var string
     */
    protected $name;

    /**
     * @ORM\Column(name="logo", type="string", length=255, nullable=true)
     * @Assert\Url()
     * 
     * @var string
     */
    protected $logo;

    /**
     * @ORM\Column(name="description", type="text", nullable=true)
     * @Assert\Length(max=200)
     * 
     * @var string
     */
    protected $description;

    /**
     * @ORM\Column(name="street", type="string", length=45, nullable=true)
     * 
     * @var string
     */
    protected $street;

    /**
     * @ORM\Column(name="city", type="string", length=45, nullable=true)
     * 
     * @var string
     */
    protected $city;

    /**
     * @ORM\Column(name="country", type="string", length=45, nullable=true)
     * 
     * @var string
     */
    protected $country;

    /**
     * @ORM\Column(name="zipcode", type="string", length=45, nullable=true)
     * 
     * @var string
     */
    protected $zipcode;

    /**
     * @ORM\Column(name="verification_status", type="boolean", nullable=true)
     * 
     * @var boolean
     */
    protected $status;

    /**
     * @ORM\OneToMany(targetEntity="Aid", mappedBy="ngo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $aids;
    
    /**
     * @ORM\OneToMany(targetEntity="UserNgo", mappedBy="ngo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $users;

    /**
     * @ORM\Column(name="website", type="string", nullable=true, length=255)
     * @Assert\Url()
     * 
     * @var boolean
     */
    protected $website;

    /**
     * @ORM\Column(name="ngo_type", type="string", length=45, nullable=false)
     * @Assert\NotBlank()
     * @Assert\Choice(callback = {"RMS\RecoveryBundle\Model\Enums", "validNgoTypes"})
     * 
     * @var string
     */
    protected $ngoType;

    /**
     * @ORM\Column(name="skills", type="simple_array", nullable=true)
     * 
     * @var array
     */
    protected $skills;
    
    /**
     * Constructor
     */
    public function __construct()
    {
        $this->aids = new ArrayCollection();
        $this->users = new ArrayCollection();
        $this->ngoType = Enums::NGO_TYPE_PRIVATE;
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Ngo
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set logo
     *
     * @param string $logo
     * @return Ngo
     */
    public function setLogo($logo)
    {
        $this->logo = $logo;

        return $this;
    }

    /**
     * Get logo
     *
     * @return string 
     */
    public function getLogo()
    {
        return $this->logo;
    }

    /**
     * Set description
     *
     * @param string $description
     * @return Ngo
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string 
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set street
     *
     * @param string $street
     * @return Ngo
     */
    public function setStreet($street)
    {
        $this->street = $street;

        return $this;
    }

    /**
     * Get street
     *
     * @return string 
     */
    public function getStreet()
    {
        return $this->street;
    }

    /**
     * Set city
     *
     * @param string $city
     * @return Ngo
     */
    public function setCity($city)
    {
        $this->city = $city;

        return $this;
    }

    /**
     * Get city
     *
     * @return string 
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set country
     *
     * @param string $country
     * @return Ngo
     */
    public function setCountry($country)
    {
        $this->country = $country;

        return $this;
    }

    /**
     * Get country
     *
     * @return string 
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set zipcode
     *
     * @param string $zipcode
     * @return Ngo
     */
    public function setZipcode($zipcode)
    {
        $this->zipcode = $zipcode;

        return $this;
    }

    /**
     * Get zipcode
     *
     * @return string 
     */
    public function getZipcode()
    {
        return $this->zipcode;
    }

    /**
     * Set status
     *
     * @param boolean $status
     * @return Ngo
     */
    public function setStatus($status)
    {
        $this->status = $status;

        return $this;
    }

    /**
     * Get status
     *
     * @return boolean 
     */
    public function getStatus()
    {
        return $this->status;
    }
    
    /**
     * @return boolean
     */
    public function isVerified()
    {
        return $this->status;
    }

    public function __toString()
    {
        return $this->name.'';
    }

    /**
     * Add aid
     *
     * @param Aid $aid
     * @return Ngo
     */
    public function addAid(Aid $aid)
    {
        $this->aids[] = $aid;

        return $this;
    }

    /**
     * Remove aid
     *
     * @param Aid $aid
     */
    public function removeAid(Aid $aid)
    {
        $this->aids->removeElement($aid);
    }

    /**
     * Get aids
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAids()
    {
        return $this->aids;
    }

    /**
     * Add user
     *
     * @param UserNgo $user
     * @return Ngo
     */
    public function addUser(UserNgo $user)
    {
        $this->users[] = $user;

        return $this;
    }

    /**
     * Remove user
     *
     * @param UserNgo $user
     */
    public function removeUser(UserNgo $user)
    {
        $this->users->removeElement($user);
    }

    /**
     * Get users
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getUsers()
    {
        return $this->users;
    }

    /**
     * @return string
     */
    public function getWebsite()
    {
        return $this->website;
    }

    public function setWebsite($website)
    {
        $this->website = $website;
    }

    public function getNgoType()
    {
        return $this->ngoType;
    }

    public function setNgoType($ngoType)
    {
        $this->ngoType = $ngoType;
        
        return $this;
    }

    /**
     * @return array
     */
    public function getSkills()
    {
        return $this->skills;
    }

    public function setSkills(array $skills)
    {
        $this->skills = $skills;
        
        return $this;
    }

    /**
     * @return boolean
     */
    public function isHealthNgo()
    {
        return $this->ngoType == Enums::NGO_TYPE_HEALTH;
    }
    
}

src/RMS/RecoveryBundle/Resources/views/AidDistribution/_js.html.twig
<script type="text/javascript">
jQuery(function($) {
    var xhr = {};
    function loadtip() {
        $('span.barangay-tip').tooltip({
            'placement' : 'right',
            'html': true
        });
    }
    loadtip();
    
    $(document).on("change", ".toggle-province", function() {
        var $this=$(this), id=$this.val();
        var prov = $("#province-main"), current = prov.data("province");
        if (current != id) {
            $(".province-main-content", prov).hide();
            $(".province-loader", prov).show();
        }
        var xp = "province";
        if(xhr[xp] && xhr[xp].readyState != 4){
            xhr[xp].abort();
        }
        xhr[xp] = $.post("{{ path('toggle_province') }}"+"?r="+Math.random(), {id:id,toggle:1}, function(data) {
            prov.replaceWith(data);
            loadtip();
        });
    });
    
    $(document).on("change", ".toggle-municipality", function() {
        var $this=$(this), id=$this.val(), toggle=this.checked?1:0;
        var muni = $("#municipality-"+id).show();
        if (!toggle) muni.hide();
        var xp = "municipality"+id;
        if(xhr[xp] && xhr[xp].readyState != 4){
            xhr[xp].abort();
        }
        xhr[xp] = $.post("{{ path('toggle_municipality') }}"+"?r="+Math.random(), {id:id,toggle:toggle}, function(data) {
            if (toggle) muni.replaceWith(data).show();
            loadtip();
        });
    });
    
    $(document).on("change", ".toggle-barangay", function() {
        var $this=$(this), id=$this.val(), toggle=this.checked?1:0;
        var bara = $("#barangay-"+id).show();
        if (!toggle) bara.hide();
        var xp = "barangay"+id;
        if(xhr[xp] && xhr[xp].readyState != 4){
            xhr[xp].abort();
        }
        xhr[xp] = $.post("{{ path('toggle_barangay') }}"+"?r="+Math.random(), {id:id,toggle:toggle}, function(data) {
            if (toggle) bara.replaceWith(data).show();
            loadtip();
        });
    });
    
    $(document).on("click", ".municipality-modal", function(e) {
        e.stopPropagation();
        var $this = $(this), id = $this.data("municipality");
        $.post("{{ path('load_summary') }}/"+id+"?r="+Math.random(), function(data) {
            $(".modal-body", "#municipality-modal-"+id).replaceWith(data);
        });
        return false;
    });
});
</script>

src/RMS/RecoveryBundle/Resources/views/AidDistribution/_loadMunicipality.html.twig
<div class="panel panel-default load" id="municipality-{{ municipality.id }}" style="display:none;">
    <div class="panel-heading">
        <h4 class="panel-title">
            <a class="load-municipality" 
               data-toggle="collapse" 
               data-municipality="{{ municipality.id }}" 
               data-province="{{ municipality.province.id }}" 
               data-parent="#province-{{ municipality.province.id }}" 
               href="#collapse-municipality-{{ municipality.id }}">
                <strong><i class="glyphicon glyphicon-collapse-up"></i> {{ municipality }}</strong>
            </a>
            <img src="{{ asset('bundles/rmsrecovery/images/ajax-loader_blue.gif') }}" alt="">
        </h4>
    </div>
</div>

src/RMS/RecoveryBundle/Resources/views/AidDistribution/_summary.html.twig
<!-- Modal -->
<div class="modal fade" id="municipality-modal-{{ municipality.id }}" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <div class="modal-label-left">
                    <h4 class="modal-title" id="myModalLabel">Municipal Summary</h4>
                </div>
                <div class="modal-label-right">
                    <h4 class="modal-title" id="myModalLabel">{{ municipality }}</h4>
                </div>
                <button data-dismiss="modal" aria-hidden="true" class="btn btn-primary btn-sm btn-modal-close">
                    <span class="glyphicon glyphicon-remove"></span>
                    Close
                </button>
            </div>
            <div class="modal-head-separator">
                <div class="row">
                    <div class="col-xs-2">
                        &nbsp;&nbsp;
                        Population: {% if municipality.population %}{{ municipality.population|number_format }}{% endif %}
                    </div>
                    <div class="col-xs-3">
                        Est. Households: {% if municipality.estimatedHouseholds %}{{ municipality.estimatedHouseholds|number_format }}{% endif %}
                    </div>
                    <div class="col-xs-3">
                        Affected Households: ~{% if municipality.affectedHouseholds %}
                            {{ municipality.affectedHouseholds|number_format }}{% endif %}
                    </div>
                    <div class="col-xs-3">
                        Aid Organizations Active: {{ municipality.activeNgos|length|number_format }}
                    </div>
                </div>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <img src="{{ asset('bundles/rmsrecovery/images/ajax-loader_blue.gif') }}" alt="">
                </div>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

src/RMS/RecoveryBundle/Resources/views/AidDistribution/_summaryContent.html.twig
<div class="table-responsive">
<table class="table table-striped table-bordered">
    <tbody><tr>
            <th width="15%">Organization</th>
            <th width="15%">Area</th>
            <th width="5%">Qty.</th>
            <th width="15%">Aid Provided</th>
            <th width="30%">Description</th>
            <th width="10%">Est. People Served</th>
            <th width="20%">Date Given</th>
            <th width="15%">Est. Supply Exhaustion</th>
        </tr>
        {% set ngo = 0 %}
        {% for aid in municipality.aids %}
        <tr>
            <td>
                <div class="row" {% if ngo == aid.ngo.id %}style="display:none;"{% endif %}>
                    <div class="col-md-4" style="margin-bottom:10px;">
                        {% if aid.ngo.logo %}
                        <img width="50" src="{{ aid.ngo.logo }}" alt="{{ aid.ngo }}" title="{{ aid.ngo }}">
                        {% endif %}
                    </div>
                    <div class="col-sm-7">
                        <strong title="{{ aid.ngo }}">{{ aid.ngo }}</strong>
                    </div>
                </div>
                {% set ngo = aid.ngo.id %}
            </td>
            <td>{{ aid.geo }}</td>
            <td>{{ aid.quantity|number_format }}</td>
            <td>{{ aid.type }}</td>
            <td>{{ aid.description }}</td>
            <td>{% if aid.peopleCatered %}{{ aid.peopleCatered|number_format }}{% endif %}</td>
            <td>{{ aid.dateStart|date('M j, Y') }}</td>
            <td>{% if aid.dateEnd %}{{ aid.dateEnd|date('M j, Y') }}{% endif %}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
</div>

src/RMS/RecoveryBundle/Resources/views/AidDistribution/_toggleProvinces.html.twig
<!-- Provinces -->
<div class="row aid-distribution-wrapper">
    <div class="toggle-provinces" data-toggle="buttons">
    {% for province in provinces %}
        <label class="btn btn-default {% if province.id in checked_provinces %}active{% endif %}">
            <a href="{{ path('aid_distribution', {provinceId:province.id}) }}">{{ province[:30] }}</a>
            <input type="radio" class="toggle-province" value="{{ province.id }}" {% if province.id in checked_provinces %}checked="checked"{% endif %}>
        </label>
    {% endfor %}
    </div>
</div>
<!-- End Provinces -->

src/RMS/RecoveryBundle/Resources/views/AidDistribution/barangayDistribution.html.twig
{% extends "RMSRecoveryBundle:AidDistribution:index.html.twig" %}

{% block aid_title %}
Aid Distribution - Barangay {{ barangay }} 
{% endblock %}

{% block aid_content %}
{% include "RMSRecoveryBundle:AidDistribution:barangayContent.html.twig" %}
{% endblock %}

src/RMS/RecoveryBundle/Resources/views/AidDistribution/index.html.twig
{% extends "RMSRecoveryBundle::layout.html.twig" %}

{% block stylesheets_custom %}
    <link rel="stylesheet" type="text/css" href="{{ asset('bundles/rmsrecovery/css/aid-distribution.css') }}" />
    {% if is_granted('ROLE_NGO') and app.user.verified %}
        <link rel="stylesheet" type="text/css" href="{{ asset('bundles/rmsrecovery/css/frontend-aid_distribution.css') }}" />
        <link href="{{ asset('bundles/rmsrecovery/datepicker/css/datepicker.css') }}" rel="stylesheet">
    {% endif %}
{% endblock stylesheets_custom %}

{% block content %}
    <div class="row aid-distribution-wrapper">
        <div class="row ph-header-2">
            <div class="col-md-6">
                <div class="page-header darkgreen">
                    <h2>{% block aid_title %}{% spaceless %}
                            Aid Distribution Overview
                        {% endspaceless %}{% endblock aid_title %}</h2>
                </div>
            </div>
            {% if is_granted('ROLE_NGO') %}
                <div class="col-md-5 col-md-offset-1">
                    {% if app.user.verified %}
                        <a href="{{ path('aid_history') }}" class="btn btn-lg btn-warning">Edit Previous Entries</a>
                        <a href="{#{ path('aid_entry') }#}" id="add-entry" class="btn btn-success btn-lg ph-btn-lg pull-right">{{ 'Show Entry Form'|trans }}</a>
                    {% else %}
                        <div class="alert alert-warning">
                            {{ 'ngo.not_verified_message'|trans|raw }}
                        </div>
                        <div class="pull-right" style="margin:-10px 0 10px 0;">
                            {% include "RMSRecoveryBundle::_livechat.html.twig" %}
                        </div>
                    {% endif %}
                </div>
            {% endif %}
        </div>
    </div>

    {% if is_granted('ROLE_NGO') and app.user.verified %}
        <div id="entry-container" style="display:none;">
            {% render(controller("RMSRecoveryBundle:AidEntry:addEntry")) %}
        </div>
    {% endif %}

    {% block aid_content %}
        {% include "RMSRecoveryBundle:AidDistribution:_toggleProvinces.html.twig" %}
        {% include "RMSRecoveryBundle:AidDistribution:provinceDistribution.html.twig" %}
    {% endblock aid_content %}

{% endblock content %}

{% block javascripts %}
    {{ parent() }}
    {% include "RMSRecoveryBundle:AidDistribution:_js.html.twig" %}
    {% if is_granted('ROLE_NGO') and app.user.verified %}
        {% include "RMSRecoveryBundle:AidEntry:_js.html.twig" %}
        {% include "RMSRecoveryBundle:Messageboard:_js.html.twig" %}
        <script type="text/javascript">
            jQuery(function($) {
                function loadpicker() {
                    try {
                        $('#entry-container .datepicker').datepicker({format: 'dd/mm/yyyy'})
                                .on('changeDate', function(ev){
                                    $('.datepicker').datepicker('hide');
                                });
                    } catch(error) {
                    }
                }
                loadpicker();

                $(document).on("submit", "#add-entry-form", function() {
                    var $this = $(this), action = $this.attr("action");
                    $(".alert-success", "#entry-container").remove();
                    $(".new-entry-loader").show();
                    $.post(action+"?r="+Math.random(), $this.serialize(), function(data) {
                        $("#entry-container").html(data);
                        loadpicker();
                    });
                    return false;
                });
            });
        </script>
    {% endif %}
{% endblock %}

src/RMS/RecoveryBundle/Resources/views/AidDistribution/toggleBarangay.html.twig
{% if barangay is defined %}
    {% include "RMSRecoveryBundle:AidDistribution:barangayContent.html.twig" %}
{% endif %}

src/RMS/RecoveryBundle/Resources/views/AidDistribution/toggleProvince.html.twig
{% if province is defined %}
    {% include "RMSRecoveryBundle:AidDistribution:provinceDistribution.html.twig" %}
{% endif %}