src/RMS/RecoveryBundle/Entity/Geo.php
<?php

namespace RMS\RecoveryBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use RMS\RecoveryBundle\Model\AidManager;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Geo
 *
 * @ORM\Table(name="geo")
 * @ORM\Entity
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="type", type="string")
 * @ORM\DiscriminatorMap({
 *      "province" = "Province",
 *      "municipality" = "Municipality",
 *      "barangay" = "Barangay",
 * })
 */
abstract class Geo extends AbstractTimestamptable implements Timestamptable
{

    /**
     * @ORM\Column(name="id", type="integer", nullable=false)
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * 
     * @var integer
     */
    protected $id;

    /**
     * @ORM\Column(name="name", type="string", length=64, nullable=false)
     * @Assert\NotBlank()
     * 
     * @var string
     */
    protected $name;

    /**
     * @ORM\Column(name="map", type="text", nullable=true)
     * 
     * @var string
     */
    protected $map;

    /**
     * @ORM\OneToMany(targetEntity="Situation", mappedBy="geo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $situations;

    /**
     * @ORM\OneToMany(targetEntity="MessageBoard", mappedBy="geo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $messages;

    /**
     * @ORM\OneToMany(targetEntity="AidNeeded", mappedBy="geo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $aidsNeeded;

    /**
     * @ORM\OneToMany(targetEntity="Aid", mappedBy="geo", cascade={"persist"})
     * 
     * @var \Doctrine\Common\Collections\Collection
     */
    protected $aids;

    /**
     * @ORM\Column(name="population", type="float", nullable=true)
     * 
     * @var float
     */
    protected $population;

    /**
     * @ORM\Column(name="estimated_households", type="integer", nullable=true)
     * 
     * @var integer
     */
    protected $estimatedHouseholds;

    /**
     * @ORM\Column(name="affected_households", type="integer", nullable=true)
     * 
     * @var integer
     */
    protected $affectedHouseholds;

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->situations = new ArrayCollection();
        $this->aidsNeeded = new ArrayCollection();
        $this->aids = new ArrayCollection();
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set name
     *
     * @param string $name
     * @return Barangay
     */
    public function setName($name)
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Get name
     *
     * @return string 
     */
    public function getName()
    {
        return $this->name;
    }

    /**
     * Set map
     *
     * @param string $map
     * @return Geo
     */
    public function setMap($map)
    {
        $this->map = $map;

        return $this;
    }

    /**
     * Get map
     *
     * @return string 
     */
    public function getMap()
    {
        return $this->map;
    }

    /**
     * Add situations
     *
     * @param Situation $situation
     * @return Geo
     */
    public function addSituation(Situation $situation)
    {
        $situation->setGeo($this);
        $this->situations[] = $situation;

        return $this;
    }

    /**
     * Remove situations
     *
     * @param Situation $situation
     */
    public function removeSituation(Situation $situation)
    {
        $this->situations->removeElement($situation);
    }

    /**
     * Get situations
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getSituations()
    {
        $situations = $this->situations->getValues();
        uasort($situations, function(Situation $a, Situation $b) {
            if ($a->getDate() == $b->getDate()) {
                return 0;
            }
            return ($a->getDate() > $b->getDate()) ? -1 : 1;
        });
        return $situations;
    }

    /**
     * Get situations
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getMessages()
    {
        $messages = $this->messages->getValues();
        uasort($messages, function(MessageBoard $a, MessageBoard $b) {
            if ($a->getDate() == $b->getDate()) {
                return 0;
            }
            return ($a->getDate() > $b->getDate()) ? -1 : 1;
        });
        return $messages;
    }

    /**
     * Add aidsNeeded
     *
     * @param AidNeeded $need
     * @return Geo
     */
    public function addNeed(AidNeeded $need)
    {
        $need->setGeo($this);
        $this->aidsNeeded[] = $need;

        return $this;
    }

    /**
     * Remove aidsNeeded
     *
     * @param AidNeeded $need
     */
    public function removeNeed(AidNeeded $need)
    {
        $this->aidsNeeded->removeElement($need);
    }

    /**
     * Get aidsNeeded
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAidsNeeded()
    {
        return $this->aidsNeeded;
    }

    /**
     * Add aid
     *
     * @param Aid $aid
     * @return Geo
     */
    public function addAid(Aid $aid)
    {
        $this->aids[] = $aid;

        return $this;
    }

    /**
     * Remove aid
     *
     * @param Aid $aid
     */
    public function removeAid(Aid $aid)
    {
        $this->aids->removeElement($aid);
    }

    /**
     * Get aids
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getAids()
    {
        return $this->sortAids($this->aids->getValues());
    }
    
    public function __toString()
    {
        return $this->id;
    }
    
    public abstract function getOptionLevel($text);
    
    public function getOptionName()
    {
        return $this->getOptionLevel('. ').' '.$this->__toString();
    }

    /**
     * Set population
     *
     * @param float $population
     * @return Barangay
     */
    public function setPopulation($population)
    {
        $this->population = $population;

        return $this;
    }

    /**
     * Get population
     *
     * @return float 
     */
    public function getPopulation()
    {
        return $this->population;
    }

    /**
     * Set estimatedHouseholds
     *
     * @param integer $estimatedHouseholds
     * @return Barangay
     */
    public function setEstimatedHouseholds($estimatedHouseholds)
    {
        $this->estimatedHouseholds = $estimatedHouseholds;

        return $this;
    }

    /**
     * Get estimatedHouseholds
     *
     * @return integer 
     */
    public function getEstimatedHouseholds()
    {
        return $this->estimatedHouseholds;
    }

    /**
     * Set affectedHouseholds
     *
     * @param integer $affectedHouseholds
     * @return Barangay
     */
    public function setAffectedHouseholds($affectedHouseholds)
    {
        $this->affectedHouseholds = $affectedHouseholds;

        return $this;
    }

    /**
     * Get affectedHouseholds
     *
     * @return integer 
     */
    public function getAffectedHouseholds()
    {
        return $this->affectedHouseholds;
    }
    
    public abstract function hasActivities(AidManager $mgr);
 
    public function lastReport()
    {
        if (count($this->aids) > 0) {
            return $this->aids->last();
        }
    }
    
    public function isProvince()
    {
        return $this instanceof Province;
    }
    
    public function isMunicipality()
    {
        return $this instanceof Municipality;
    }
    
    public function isBarangay()
    {
        return $this instanceof Barangay;
    }
    
    public function getActiveNgos()
    {
        $result = array();
        foreach ($this->aids->getValues() as $aid) {
            $ngo = $aid->getNgo();
            $result[$ngo->getId()] = $ngo;
        }
        return $result;
    }
    
    protected function sortAids($aids)
    {
        $sorter = function(Aid $a, Aid $b) {
            if ($a->getDateStart() == $b->getDateStart()) {
                return 0;
            }
            return ($a->getDateStart() > $b->getDateStart()) ? -1 : 1;
        };
        uasort($aids, $sorter);
        return $aids;
    }

    /**
     * @return integer
     */
    public abstract function getMapZoom();
    
    public function getLatitude()
    {
        $coords = $this->getCoords();
        if (!$coords || count($coords) == 0) {
            return '10.633614991656064';
        }
        $l = array();
        foreach ($coords as $c) $l[] = $c->lat;
        return array_sum($l)/count($l);
    }
    
    public function getLongitude()
    {
        $coords = $this->getCoords();
        if (!$coords || count($coords) == 0) {
            return '123.93951416015626';
        }
        $l = array();
        foreach ($coords as $c) $l[] = $c->lng;
        return array_sum($l)/count($l);
    }
    
    public function getCoords()
    {
        if ($this->map) {
            $coords = array();
            $latlng = explode(';', $this->map);
            foreach ($latlng as $ll) {
                list($lat,$lng) = explode(',', $ll);
                $coords[] = (object) array('lat' => $lat, 'lng' => $lng);
            }
            return $coords;
        }
    }
}

src/RMS/RecoveryBundle/Resources/views/Admin/form_admin_fields.html.twig
{% extends 'SonataDoctrineORMAdminBundle:Form:form_admin_fields.html.twig' %}

{% block form_row %}
    {% if sonata_admin is not defined or not sonata_admin_enabled or not sonata_admin.field_description %}
        <div class="control-group {% if errors|length > 0%} error{% endif %}">
            {{ form_label(form, label|default(null)) }}
            <div class="controls">
                {{ form_widget(form) }}
                {% if errors|length > 0 %}
                    <div class="help-inline sonata-ba-field-error-messages">
                        {{ form_errors(form) }}
                    </div>
                {% endif %}
            </div>
        </div>
    {% else %}
        <div class="control-group{% if errors|length > 0%} error{%endif%}" id="sonata-ba-field-container-{{ id }}">
            {% block label %}
                {% if sonata_admin.field_description.options.name is defined %}
                    {{ form_label(form, sonata_admin.field_description.options.name, { 'attr' : {'class' : 'control-label'} }) }}
                {% else %}
                    {{ form_label(form, label|default(null), { 'attr' : {'class' : 'control-label'} }) }}
                {% endif %}
            {% endblock %}

            {% set has_label = sonata_admin.field_description.options.name is defined or label is not sameas(false) %}
            <div class="controls sonata-ba-field sonata-ba-field-{{ sonata_admin.edit }}-{{ sonata_admin.inline }} {% if errors|length > 0 %}sonata-ba-field-error{% endif %} {% if not has_label %}sonata-collection-row-without-label{% endif %}">

                {{ form_widget(form) }}

                {% if errors|length > 0 %}
                    <div class="help-inline sonata-ba-field-error-messages">
                        {{ form_errors(form) }}
                    </div>
                {% endif %}

                {% if sonata_admin.field_description.help %}
                    <span class="help-block sonata-ba-field-help">{{ sonata_admin.admin.trans(sonata_admin.field_description.help, {}, sonata_admin.field_description.translationDomain)|raw }}</span>
                {% endif %}
            </div>
        </div>
    {% endif %}
{% endblock form_row %}

src/RMS/RecoveryBundle/Resources/views/Admin/map.html.twig
{% extends "SonataAdminBundle:CRUD:edit.html.twig" %}

{% block formactions %}

<div class="control-group">
    <div class="controls sonata-ba-field sonata-ba-field-standard-natural  ">
        <div id="map" class="span10"></div>
    </div>
</div>
<div class="control-group">
    <div class="controls sonata-ba-field sonata-ba-field-standard-natural  ">
        <button onclick="clear_markers();" class="btn btn-warning" type="button">{{ 'Clear Markers'|trans }}</button>
    </div>
</div>

<script type="text/javascript">
    var map = L.map('map').setView([{{ object.latitude }}, {{ object.longitude }}], {{ object.mapZoom }});
    L.tileLayer('http://{s}.tile.cloudmade.com/{{ map_apikey|upper }}/997/256/{z}/{x}/{y}.png', {
        attribution: 'Geocode Mapper &copy; <a href="http://www.arcanys.com">Arcanys Inc.</a>, Imagery &copy; <a href="http://cloudmade.com">CloudMade</a>',
        maxZoom: 18
    }).addTo(map);
    var markers = [];
    var polygon;
    
    var get_coords = function() {
        var out = [], row, ll;
        for (x in markers)
        {                
            ll = markers[x].getLatLng();
            row = [ll.lat, ll.lng];
            out.push(row.join(","));
        }
        jQuery(".edit-map").val(out.join(";"));
    }
    
    var addMarker = function(e){
        var marker = new L.marker(
                        e.latlng, {
                            draggable: true
                        }
                    ).on('dragend', moveMarker)                        
                    .addTo(map);
        markers[marker._leaflet_id] = marker;
        displayArea();
        get_coords();
    };

    var moveMarker = function(e){
        markers[e.target._leaflet_id] = e.target;
        displayArea();
    }

    var clear_markers = function(){
        for( x in markers ) {
            map.removeLayer(markers[x]);
        }
        markers = [];
        displayArea();
        jQuery(".edit-map").val("");
    };

    var displayArea = function() {            
        if ( typeof polygon != 'undefined' ) {
            map.removeLayer(polygon);
        }
        var coords = [];
        for( x in markers ) {
            var latlng = markers[x].getLatLng();
            coords.push([latlng.lat, latlng.lng]);
        }
        polygon = L.polygon( coords ).addTo(map);            
    }
    
    var addCoord = function(lat, lng) {
        var latlng = new L.LatLng(lat, lng);
        var marker = new L.marker(
                        latlng, {
                            draggable: true
                        }
                    ).on('dragend', moveMarker)                        
                    .addTo(map);
        markers[marker._leaflet_id] = marker;
    }
    {% if object.coords %}
        {% for coord in object.coords %}
            addCoord({{ coord.lat }}, {{ coord.lng }});
        {% endfor %}
        displayArea();
    {% endif %}

    map.on('click', addMarker);
</script>

{{ parent() }}
{% endblock %}


{% block javascripts %}
{{ parent() }}
<script src="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.js"></script>
{% endblock %}

{% block stylesheets %}
{{ parent() }}
<link rel="stylesheet" href="http://cdn.leafletjs.com/leaflet-0.6.4/leaflet.css" />
<style type="text/css">
    #map { height: 500px; }
</style>
{% endblock %}

src/RMS/RecoveryBundle/Resources/views/Admin/mapGoogle.html.twig
{% extends "SonataAdminBundle:CRUD:edit.html.twig" %}

{% block formactions %}

<div class="control-group">
    <div class="controls sonata-ba-field sonata-ba-field-standard-natural  ">
        <div id="map" class="span10"></div>
    </div>
</div>
<div class="control-group">
    <div class="controls sonata-ba-field sonata-ba-field-standard-natural  ">
        <button onclick="clearMarkers();" class="btn btn-warning" type="button">{{ 'Clear Markers'|trans }}</button>
    </div>
</div>

<script type="text/javascript">

    /*var map = L.map('map').setView([{{ object.latitude }}, {{ object.longitude }}], {{ object.mapZoom }});
    L.tileLayer('http://{s}.tile.cloudmade.com/{{ map_apikey|upper }}/997/256/{z}/{x}/{y}.png', {
        attribution: 'Geocode Mapper &copy; <a href="http://www.arcanys.com">Arcanys Inc.</a>, Imagery &copy; <a href="http://cloudmade.com">CloudMade</a>',
        maxZoom: 18
    }).addTo(map);
    var markers = [];
    var polygon;*/

	var map;
	var markers = [];
	var polygon;

	function initialize()
	{
		map = new google.maps.Map(document.getElementById('map'), {
				zoom: 8,
				center: new google.maps.LatLng("{{ object.latitude }}", "{{ object.longitude }}"),
			});

		populate_markers();

		google.maps.event.clearListeners(map, 'click');
		google.maps.event.addListener(map, 'click', function(event) {
			addMarker(event.latLng);
		});
	}

	function addMarker(latlng)
	{
		var marker = new google.maps.Marker({
			position: latlng,
			map: map,
		});

		markers.push(marker);
		displayArea();
		getCoords();
    };

    function getCoords()
	{
        var out = [], row, ll;
        for (x in markers)
        {
            ll = markers[x].getPosition();
            row = [ll.lat(), ll.lng()];
            out.push(row.join(","));
        }
        $(".edit-map").val(out.join(";"));
    }

	function clearMarkers()
    {
		if( polygon != undefined )
			polygon.setMap(null);

		for( var x in markers )
		{
			markers[x].setMap(null);
		}
		markers = [];
		$(".edit-map").val("");
    };

	function displayArea()
    {
		if ( typeof polygon != 'undefined' ) {
			polygon.setMap(null);
		}
		var coords = [];
		for( var x in markers )
		{
			var position = markers[x].getPosition();
			coords.push(position);
		}

		polygon = new google.maps.Polygon({
			path:coords,
			strokeColor:"#0000FF",
			strokeOpacity:0.8,
			strokeWeight:2,
			fillColor:"#0000FF",
			fillOpacity:0.4
		});
		polygon.setMap(map);
    }

	function populate_markers()
	{
		{% if object.coords %}
			{% for coord in object.coords %}

				addMarker( new google.maps.LatLng("{{ coord.lat }}", "{{ coord.lng }}") );

			{% endfor %}

			displayArea();

		{% endif %}
	}

	google.maps.event.addDomListener(window, 'load', initialize);
</script>

{{ parent() }}
{% endblock %}


{% block javascripts %}
{{ parent() }}
<script src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBszpleZa-a3Gux2IclWGDp6sYTyaKa0cE&sensor=false"></script>
{% endblock %}

{% block stylesheets %}
{{ parent() }}
<style type="text/css">
    #map { height: 500px; }
	.sonata-bc img{
		max-width: none;
	}
</style>
{% endblock %}

src/RMS/RecoveryBundle/Resources/views/Admin/standard_layout.html.twig
{% extends 'SonataAdminBundle::standard_layout.html.twig' %}

{% block sonata_top_bar_search %}
{% endblock %}

{% block sonata_nav_menu %}
{{ parent() }}
<ul class="nav navbar-nav pull-right">
    <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ app.user.firstname }} <span class="caret"></span></a>
        <ul class="dropdown-menu">
            <li><a href="{{ path('admin_rms_recovery_useradmin_edit', {id:app.user.id}) }}">{{ 'Profile'|trans }}</a></li>
            <li class="divider"></li>
            <li><a href="{{ path('logout') }}">{{ 'Logout'|trans }}</a></li>
        </ul>
    </li>
</ul>
{% endblock %}